language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - FLASK="Flask==0.12"
  - FLASK="Flask==0.11"
  - FLASK="Flask==0.10"

install:
  - pip install $FLASK
  - pip install pillow

script:
  - python setup.py test

branches:
  only:
    - master
