language: python

python:
  - 2.7

env:
  - FLASK="Flask==0.10"
  - FLASK="Flask==0.9"

install:
  - pip install $FLASK
  - pip install pillow

script:
  - nosetests flask_thumbnails/tests.py

branches:
  only:
    - master
